version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
