version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    volumes:
      - .:/app
      - db:/data/db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  db:
