FROM node:latest

RUN apt-get update && apt-get install nano tree -y

## run as non-root user -- this maybe should be elsewhere
RUN groupadd -r nodejs \
   && useradd -m -r -g nodejs nodejs

USER nodejs
##

RUN mkdir app
WORKDIR /app

COPY ./package*.json ./
RUN npm install -g

COPY ./ ./

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV development

EXPOSE 3030

CMD ["npm", "start"]