version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    env_file:
      - .env